version: '2'
services:
  teamspeak:
    tty: true
    image: eosystems/teamspeak
    build: build/teamspeak
    volumes:
      - teamspeak_volume:/teamspeak3
    ports:
      - "9987:9987"
      - "30033:30033"
      - "10011:10011"
      - "41144:41144"

    container_name: teamspeak

volumes:
  teamspeak_volume:
    driver: local
